[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = "0.32.0"
indoc = "2.0.7"
itertools = "0.14.0"
memoize = "0.5.1"
microlp = "0.2.11"
num = "0.4.3"
rayon = "1.11.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
